name: Conductino Study Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK tools
        run: |
          sdkmanager "platforms;android-36"
          sdkmanager "ndk;29.0.14206865"
          sdkmanager "cmake;3.22.1"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Prepare release directory
        run: |
          mkdir -p release

          cp app/build/outputs/apk/debug/app-debug.apk \
            release/Conductino-Study-${GITHUB_REF_NAME#v}-debug.apk

          cp app/build/outputs/apk/release/app-release.apk \
            release/Conductino-Study-${GITHUB_REF_NAME#v}-release-unsigned.apk

      - name: Create ZIP
        run: |
          cd release
          zip "Conductino-Study-${GITHUB_REF_NAME#v}.zip" *.apk

      - name: Prepare release notes
        run:
          VERSION="${GITHUB_REF_NAME#v"

          cp "release_notes/v${VERSION.md}" release_notes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/*.apk
            release/*.zip
          body_path: release_notes.md
          prerelease: ${{ contains(github.ref_name, '-') }}